import {chromium} from '@playwright/test';
import {readdirSync} from 'node:fs';
import {writeFile} from 'node:fs/promises';
import path from 'node:path';
import {basePath} from '../../scripts/repository-path.mjs';

const root=process.cwd(),evidence=path.resolve(root,'artifacts/board-controls-simplification'),asset=()=>`${basePath}assets/${readdirSync(path.join(root,'dist/assets')).find(file=>file.startsWith('cloud-ui-')&&file.endsWith('.js'))}`,origin=process.env.PLAYWRIGHT_BASE_URL||'http://127.0.0.1:4190',browser=await chromium.launch({headless:true,executablePath:process.env.PLAYWRIGHT_EXECUTABLE_PATH||'C:/Program Files (x86)/Google/Chrome/Application/chrome.exe'}),captures=[];

async function fresh(viewport){const context=await browser.newContext({viewport});const page=await context.newPage(),errors={console:[],page:[],requests:[]};page.on('console',message=>{if(message.type()==='error')errors.console.push(message.text());});page.on('pageerror',error=>errors.page.push(error.message));page.on('requestfailed',request=>errors.requests.push({host:new URL(request.url()).host,error:request.failure()?.errorText||'failed'}));await page.goto(`${origin}${basePath}`,{waitUntil:'networkidle'});await page.waitForFunction(()=>globalThis.FlowboardApp&&globalThis.FlowboardState);return{context,page,errors};}
async function finish(label,entry,shot){const metrics=await entry.page.evaluate(()=>({viewport:{width:innerWidth,height:innerHeight},documentWidth:document.documentElement.scrollWidth,viewportWidth:innerWidth,mode:globalThis.FlowboardApp.getMode().kind,visibleText:document.body.innerText.slice(0,500)}));await entry.page.screenshot({path:path.join(evidence,shot),fullPage:false});captures.push({label,shot,metrics,errors:entry.errors});await entry.context.close();}
async function installDirectory(page){await page.evaluate(async({module})=>{globalThis.FlowboardApp={getMode:()=>({kind:'cloud',id:'personal-synthetic',personalWorkspaceId:'personal-synthetic',role:'owner'}),getActiveBoardId:()=>'',openCloudWorkspace:()=>{},openCloudPreview:()=>{},selectBoard:()=>{},createBoard:()=>false};const entry={id:'personal-synthetic',name:'My workspace',ownerUid:'synthetic-owner',role:'owner',status:'ready',personal:true,migration:{state:'verified'},hasMore:false,boards:[]};const{initializeCloudWorkspaceUI}=await import(module);initializeCloudWorkspaceUI({localAdapter:{inspectLegacyWorkspace:()=>({status:'none',counts:{boards:0}})},cloudAdapter:{listBoardDirectory:async()=>[entry]}}).setSession({uid:'synthetic-owner'});document.querySelector('#boards-button').disabled=false;},{module:asset()});}
async function installMembers(page,role='owner'){await page.evaluate(async({module,role})=>{globalThis.FlowboardApp={getMode:()=>({kind:role==='viewer'?'cloud-preview':'cloud',id:'members-synthetic',role})};const adapter={listMembers:async()=>role==='viewer'?[{uid:'viewer',displayName:'Synthetic Viewer',role:'viewer'}]:[{uid:'owner',displayName:'Synthetic Owner',role:'owner'},{uid:'editor',displayName:'Synthetic Editor',role:'editor'}],listInvites:async()=>[],createInvite:async()=>({url:'https://example.test/invite'}),revokeInvite:async()=>{},changeMemberRole:async()=>{},removeMember:async()=>{},leaveWorkspace:async()=>{},transferOwnership:async()=>{}};const{initializeMembersUI}=await import(module);initializeMembersUI(adapter).setSession({uid:role==='viewer'?'viewer':'owner',displayName:role==='viewer'?'Synthetic Viewer':'Synthetic Owner',email:'synthetic@example.test'});document.querySelector('#open-workspace-members').hidden=false;document.querySelector('#workspace-dialog').showModal();},{module:asset(),role});}

let entry=await fresh({width:1440,height:900});await installDirectory(entry.page);await entry.page.getByRole('button',{name:'Boards'}).click();await entry.page.getByRole('dialog',{name:'Your boards'}).waitFor();await entry.page.locator('#new-board-form').waitFor();await finish('Your boards with the single lower creation form',entry,'final-your-boards.png');
entry=await fresh({width:1440,height:900});await entry.page.evaluate(()=>FlowboardApp.openCloudWorkspace(FlowboardState.makeWorkspace(),{id:'capture-board',name:'Synthetic board',role:'owner'}));await entry.page.locator('#board .list').first().waitFor();await finish('Board view toolbar with direct Archived cards',entry,'final-toolbar-board.png');
entry=await fresh({width:1440,height:900});await entry.page.evaluate(()=>FlowboardApp.openCloudWorkspace(FlowboardState.makeWorkspace(),{id:'capture-list',name:'Synthetic board',role:'owner'}));await entry.page.locator('#board .list').first().waitFor();await entry.page.locator('#view-toggle').click();await entry.page.locator('#list-view-table').waitFor();await finish('List view toolbar with direct Archived cards',entry,'final-toolbar-list.png');
entry=await fresh({width:1440,height:900});const populated=await entry.page.evaluate(()=>{const value=FlowboardState.makeWorkspace(),card=FlowboardState.makeCard('Archived synthetic card');card.archived=true;card.archivedAt=new Date().toISOString();value.boards[0].lists[0].cards.push(card);return value;});await entry.page.evaluate(value=>FlowboardApp.openCloudWorkspace(value,{id:'capture-archive',name:'Synthetic board',role:'owner'}),populated);await entry.page.locator('#board .list').first().waitFor();await entry.page.locator('#archived-cards-button').click();await entry.page.getByRole('dialog',{name:'Archived cards'}).waitFor();await finish('Populated Archived cards dialog',entry,'final-archive-populated.png');
entry=await fresh({width:1440,height:900});await entry.page.evaluate(()=>FlowboardApp.openCloudWorkspace(FlowboardState.makeWorkspace(),{id:'capture-empty-archive',name:'Synthetic board',role:'owner'}));await entry.page.locator('#board .list').first().waitFor();await entry.page.locator('#archived-cards-button').click();await entry.page.getByRole('dialog',{name:'Archived cards'}).waitFor();await finish('Empty Archived cards dialog',entry,'final-archive-empty.png');
entry=await fresh({width:1440,height:900});await installMembers(entry.page,'owner');await entry.page.getByRole('button',{name:'Manage members'}).click();await entry.page.getByRole('dialog',{name:'People and invitations'}).waitFor();await finish('Board access at desktop width',entry,'final-board-access-1440.png');
entry=await fresh({width:680,height:793});await installMembers(entry.page,'owner');await entry.page.getByRole('button',{name:'Manage members'}).click();await entry.page.getByRole('dialog',{name:'People and invitations'}).waitFor();await finish('Board access at resized screenshot width',entry,'final-board-access-680.png');
entry=await fresh({width:390,height:844});await installMembers(entry.page,'owner');await entry.page.getByRole('button',{name:'Manage members'}).click();await entry.page.getByRole('dialog',{name:'People and invitations'}).waitFor();await finish('Board access stacked phone layout',entry,'final-board-access-390.png');
entry=await fresh({width:320,height:720});await installDirectory(entry.page);await entry.page.getByRole('button',{name:'Boards'}).click();await entry.page.getByRole('dialog',{name:'Your boards'}).waitFor();await finish('Your boards narrow layout with lower form',entry,'final-your-boards-320.png');
await writeFile(path.join(evidence,'final-captures.json'),JSON.stringify({count:captures.length,captures,boundary:'Fresh anonymous/synthetic browser contexts only; no sign-in, production board, or cloud mutation.'},null,2)+'\n');console.log(JSON.stringify({count:captures.length,captures},null,2));await browser.close();
