import {test,expect} from '@playwright/test';
import {createRequire} from 'node:module';
import {basePath} from '../scripts/repository-path.mjs';
const require=createRequire(import.meta.url),axePath=require.resolve('axe-core/axe.min.js');
const audit=async page=>{await page.addScriptTag({path:axePath});return page.evaluate(async()=>{const result=await axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa']}});return result.violations.map(item=>({id:item.id,nodes:item.nodes.length}));});};

test('loaded cloud board and card dialog have no axe violations',async({page})=>{
  const errors=[];page.on('pageerror',error=>errors.push(error.name));page.on('console',message=>{if(message.type()==='error')errors.push('console');});await page.goto(basePath);await page.waitForFunction(()=>globalThis.FlowboardApp&&globalThis.FlowboardState);await page.evaluate(()=>{const workspace=FlowboardState.makeEmptyWorkspace(),board=FlowboardState.makeBoard('blank'),card=FlowboardState.makeCard('Accessible card');board.title='Accessibility board';board.lists=[FlowboardState.makeList('Accessible list',[card])];workspace.boards=[board];workspace.activeBoardId=board.id;FlowboardApp.openCloudWorkspace(workspace,{id:'a11y-workspace',name:'Accessibility workspace',role:'owner'});});expect(await audit(page)).toEqual([]);await page.locator('.card-open').click();await expect(page.locator('#card-dialog')).toBeVisible();expect(await audit(page)).toEqual([]);expect(errors).toEqual([]);
});

test('cloud-first board manager and Data recovery dialogs have no axe violations',async({page})=>{
  const errors=[];page.on('pageerror',error=>errors.push(error.name));page.on('console',message=>{if(message.type()==='error')errors.push('console');});await page.goto(basePath);await page.waitForFunction(()=>globalThis.FlowboardApp&&globalThis.FlowboardState);await expect(page.locator('#account-button')).toHaveText('Sign in');await page.evaluate(()=>{const dialog=document.querySelector('#workspace-dialog'),list=document.querySelector('#workspace-board-list'),row=document.createElement('div'),title=document.createElement('strong'),detail=document.createElement('span'),open=document.createElement('button');row.className='workspace-entry';title.textContent='A11y board';detail.textContent='A11y personal · owner · Position 1';open.type='button';open.textContent='Open';open.setAttribute('aria-label','Open A11y board in A11y personal, position 1');row.append(title,detail,open);list.replaceChildren(row);document.querySelector('#new-board-button').hidden=false;dialog.showModal();});await page.setViewportSize({width:960,height:720});const boards=page.locator('#workspace-dialog');await expect(boards).toBeVisible();const newBoard=boards.getByRole('button',{name:'+ New board'}),box=await newBoard.boundingBox();expect(box?.x).toBeGreaterThanOrEqual(0);expect(box?.x+box?.width).toBeLessThanOrEqual(960);expect(await audit(page)).toEqual([]);await page.evaluate(()=>{const dialog=document.querySelector('#workspace-dialog');document.querySelector('#workspace-heading').textContent='Data recovery';document.querySelector('#legacy-spaces-section').hidden=false;document.querySelector('#legacy-spaces-section').open=true;document.querySelector('#workspace-board-list').closest('section').hidden=true;document.querySelector('#archived-board-section').hidden=true;document.querySelector('#workspace-search').closest('label').hidden=true;document.querySelector('#new-board-form').hidden=true;});const recovery=page.getByRole('dialog',{name:'Data recovery'});await expect(recovery).toBeVisible();expect(await audit(page)).toEqual([]);expect(errors).toEqual([]);
});
