import {test,expect} from '@playwright/test';
import {createRequire} from 'node:module';
import {readdirSync} from 'node:fs';
import {basePath} from '../scripts/repository-path.mjs';
const require=createRequire(import.meta.url),axePath=require.resolve('axe-core/axe.min.js');
const builtCloudAsset=()=>`${basePath}assets/${readdirSync('dist/assets').find(file=>file.startsWith('cloud-ui-')&&file.endsWith('.js'))}`;
const audit=async page=>{await page.addScriptTag({path:axePath});return page.evaluate(async()=>{const result=await axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa']}});return result.violations.map(item=>({id:item.id,nodes:item.nodes.length}));});};

test('loaded cloud board and card dialog have no axe violations',async({page})=>{
  const errors=[];page.on('pageerror',error=>errors.push(error.name));page.on('console',message=>{if(message.type()==='error')errors.push('console');});await page.goto(basePath);await page.waitForFunction(()=>globalThis.FlowboardApp&&globalThis.FlowboardState);await page.evaluate(()=>{const workspace=FlowboardState.makeEmptyWorkspace(),board=FlowboardState.makeBoard('blank'),card=FlowboardState.makeCard('Accessible card');board.title='Accessibility board';board.lists=[FlowboardState.makeList('Accessible list',[card])];workspace.boards=[board];workspace.activeBoardId=board.id;FlowboardApp.openCloudWorkspace(workspace,{id:'a11y-workspace',name:'Accessibility workspace',role:'owner'});});expect(await audit(page)).toEqual([]);await page.locator('.card-open').click();await expect(page.locator('#card-dialog')).toBeVisible();expect(await audit(page)).toEqual([]);expect(errors).toEqual([]);
});

test('cloud-first Account, Boards, and account repair states have no axe violations',async({page})=>{
  const errors=[];page.on('pageerror',error=>errors.push(error.name));page.on('console',message=>{if(message.type()==='error')errors.push('console');});await page.goto(basePath);await page.waitForFunction(()=>globalThis.FlowboardApp&&globalThis.FlowboardState);await page.locator('#account-button').click();await expect(page.getByRole('dialog',{name:'Sign in'})).toBeVisible();expect(await audit(page)).toEqual([]);await page.getByRole('button',{name:'Close account'}).click();
  await page.evaluate(async asset=>{globalThis.FlowboardApp={getMode:()=>({kind:'needs-recovery',id:'invalid-source',personalWorkspaceId:'invalid-source',role:'owner',message:'Account setup needs attention.'}),getActiveBoardId:()=>'',openCloudWorkspace:()=>{},openCloudPreview:()=>{},selectBoard:()=>{},createBoard:()=>false,retryAccountSetup:()=>{},setSession:()=>{}};const {initializeCloudWorkspaceUI}=await import(asset);initializeCloudWorkspaceUI({localAdapter:{inspectLegacyWorkspace:()=>({status:'none',counts:{boards:0}})},cloudAdapter:{listBoardDirectory:async()=>[{id:'invalid-source',name:'Invalid source',ownerUid:'owner',role:'owner',status:'ready',personal:false,migration:{state:'verified'},boards:[],hasMore:false}]}}).setSession({uid:'owner'});document.querySelector('#boards-button').disabled=false;},builtCloudAsset());
  await page.setViewportSize({width:960,height:720});await page.getByRole('button',{name:'Boards'}).click();const manager=page.getByRole('dialog',{name:'Your boards'});await expect(manager).toBeVisible();await expect(manager.getByRole('button',{name:'Repair account setup'})).toBeVisible();expect(await audit(page)).toEqual([]);await manager.getByRole('button',{name:'Repair account setup'}).click();await expect(page.getByRole('dialog',{name:'Repair account setup?'})).toBeVisible();expect(await audit(page)).toEqual([]);expect(errors).toEqual([]);
});
