import {test,expect} from '@playwright/test';
import {basePath} from '../scripts/repository-path.mjs';
const paletteTones={standard:{light:['#edf1f6','#edf1f6'],dark:['#1d293b','#1d293b']},'frost-blue':{light:['#d5e2ef','#dcdfef'],dark:['#132033','#1e1e39']},'soft-sage':{light:['#f6faf7','#f1f7f6'],dark:['#152224','#1a2628']},'warm-sand':{light:['#fcf9f5','#f9f5f1'],dark:['#1d1f21','#222224']},lavender:{light:['#f9f8fc','#f5f7fb'],dark:['#1a1e2b','#1d2434']},'mist-slate':{light:['#d9e2ea','#dcdfe7'],dark:['#13202d','#1a2432']},'blush-clay':{light:['#f2e4df','#f6ebe7'],dark:['#272020','#302629']},'pale-aqua':{light:['#e0efed','#e8f5f3'],dark:['#1c2b2d','#213638']}};
const colors=Object.keys(paletteTones);
async function openReady(page){await page.goto(basePath);await page.waitForFunction(()=>globalThis.FlowboardApp&&globalThis.FlowboardState&&['signed-out','unavailable','cloud','cloud-preview','ready-empty'].includes(globalThis.FlowboardApp.getMode().kind));}
async function openSyntheticBoard(page,workspaceId='synthetic-workspace'){
  await page.evaluate(({workspaceId,workspaceSentinel,appearanceSentinel})=>{
    localStorage.setItem('flowboard-workspace',workspaceSentinel);localStorage.setItem('flowboard-appearance',appearanceSentinel);
    const workspace=FlowboardState.makeWorkspace(),board=workspace.boards[0],template=structuredClone(board.lists[0]);board.id='synthetic-board';board.lists=['list-a','list-b','list-c'].map((id,index)=>({...structuredClone(template),id,title:`Synthetic List ${index+1}`,cards:[]}));workspace.activeBoardId=board.id;
    FlowboardApp.openCloudPreview(workspace,{id:workspaceId,name:'Synthetic preview',role:'viewer'});
  },{workspaceId,workspaceSentinel:'{"sentinel":"synthetic-workspace-bytes"}',appearanceSentinel:'{"sentinel":"synthetic-global-appearance-bytes"}'});
}
const openMenu=(page,title='Synthetic List 1')=>page.getByRole('button',{name:`Open actions for ${title}`}).click();
const openAppearance=async(page,title='Synthetic List 1')=>{await openMenu(page,title);await page.locator('.list-menu-panel:visible').getByRole('menuitem',{name:'List appearance'}).click();await expect(page.getByRole('dialog')).toBeVisible();};

 test('read-only list menu exposes browser-local appearance and the eight-color matrix',async({page})=>{
  const errors=[];page.on('pageerror',()=>errors.push('page'));
  await openReady(page);await openSyntheticBoard(page);await openMenu(page);
  const menu=page.locator('.list-menu-panel:visible');await expect(menu.getByRole('menuitem',{name:'Rename list'})).toBeDisabled();await expect(menu.getByRole('menuitem',{name:'Move left'})).toBeDisabled();await expect(menu.getByRole('menuitem',{name:'Move right'})).toBeDisabled();await expect(menu.getByRole('menuitem',{name:'Delete list'})).toBeDisabled();await expect(menu.getByRole('menuitem',{name:'List appearance'})).toBeEnabled();
  await menu.getByRole('menuitem',{name:'List appearance'}).click();const dialog=page.getByRole('dialog');await expect(dialog.getByRole('heading',{name:'Appearance for Synthetic List 1'})).toBeVisible();expect(await dialog.locator('.appearance-palettes').evaluate(el=>getComputedStyle(el).display)).toBe('grid');await expect(dialog.getByText('Only in this browser. Others see their own.')).toBeVisible();await expect(dialog.locator('[name="list-color"]')).toHaveCount(8);await expect(dialog.locator('[name="list-finish"]')).toHaveCount(2);
  for(const mode of ['light','dark']){await page.evaluate(mode=>{document.documentElement.dataset.theme=mode;window.dispatchEvent(new Event('flowboard:appearance-change'));},mode);for(const color of colors){const palette=paletteTones[color];await dialog.locator(`[name="list-color"][value="${color}"]`).check();for(const finish of ['solid','gradient']){await dialog.locator(`[name="list-finish"][value="${finish}"]`).check();const actual=await page.locator('.list').first().evaluate(el=>({color:el.dataset.listColor,finish:el.dataset.listFinish,background:el.style.getPropertyValue('--list-background')}));expect(actual.color).toBe(color);expect(actual.finish).toBe(finish);if(color==='standard')expect(actual.background).toBe(mode==='dark'?'#1d293b':'#edf1f6');else{expect(actual.background).toContain(palette[mode][0]);expect(actual.background).toContain(palette[mode][1]);if(finish==='gradient')expect(actual.background).toContain('linear-gradient');else expect(actual.background).toContain('color-mix');}expect(await page.locator('.list').nth(1).getAttribute('data-list-color')).toBe('standard');}}}
  await dialog.locator('[name="list-color"][value="blush-clay"]').check();await dialog.locator('[name="list-finish"][value="gradient"]').check();await dialog.getByRole('button',{name:'Save list appearance'}).click();await expect(dialog).toBeHidden();await expect(page.locator('.list').first().locator('.list-menu')).toBeFocused();
  const stored=await page.evaluate(()=>({workspace:localStorage.getItem('flowboard-workspace'),appearance:localStorage.getItem('flowboard-appearance'),overrides:JSON.parse(localStorage.getItem('flowboard-list-appearances'))}));expect(stored.workspace).toBe('{"sentinel":"synthetic-workspace-bytes"}');expect(stored.appearance).toBe('{"sentinel":"synthetic-global-appearance-bytes"}');expect(stored.overrides).toEqual({version:1,overrides:[{workspaceId:'synthetic-workspace',boardId:'synthetic-board',listId:'list-a',color:'blush-clay',finish:'gradient'}]});expect(errors).toEqual([]);
  await openReady(page);await openSyntheticBoard(page);await expect(page.locator('.list').first()).toHaveAttribute('data-list-color','blush-clay');await expect(page.locator('.list').first()).toHaveAttribute('data-list-finish','gradient');await expect(page.locator('.list').nth(1)).toHaveAttribute('data-list-color','standard');
});

test('global defaults update inheriting lists without changing list overrides or workspace scope',async({page})=>{
  await openReady(page);await openSyntheticBoard(page);
  await openMenu(page,'Synthetic List 2');await page.locator('.list-menu-panel:visible').getByRole('menuitem',{name:'List appearance'}).click();await page.locator('[name="list-color"][value="blush-clay"]').check();await page.locator('[name="list-finish"][value="gradient"]').check();await page.getByRole('button',{name:'Save list appearance'}).click();
  const canvas=await page.locator('html').getAttribute('data-canvas');await page.getByRole('button',{name:'Open appearance settings'}).click();const global=page.getByRole('dialog');await global.locator('[name="appearance-list-color"][value="frost-blue"]').check();await global.locator('[name="appearance-list-finish"][value="solid"]').check();await global.locator('[name="appearance-canvas"][value="lagoon"]').check();await global.getByRole('button',{name:'Save appearance'}).click();
  await expect(page.locator('.list').nth(0)).toHaveAttribute('data-list-color','frost-blue');await expect(page.locator('.list').nth(0)).toHaveAttribute('data-list-finish','solid');await expect(page.locator('.list').nth(1)).toHaveAttribute('data-list-color','blush-clay');await expect(page.locator('.list').nth(1)).toHaveAttribute('data-list-finish','gradient');await expect(page.locator('.list').nth(2)).toHaveAttribute('data-list-color','frost-blue');await expect(page.locator('html')).toHaveAttribute('data-canvas','lagoon');
  await openAppearance(page,'Synthetic List 2');await page.getByRole('button',{name:'Use default appearance'}).click();await page.getByRole('button',{name:'Save list appearance'}).click();await expect(page.locator('.list').nth(1)).toHaveAttribute('data-list-color','frost-blue');
  await page.evaluate(()=>{const workspace=FlowboardState.makeWorkspace(),board=workspace.boards[0],template=structuredClone(board.lists[0]);board.id='synthetic-board';board.lists=['list-a','list-b','list-c'].map((id,index)=>({...structuredClone(template),id,title:`Synthetic List ${index+1}`,cards:[]}));workspace.activeBoardId=board.id;FlowboardApp.openCloudPreview(workspace,{id:'another-synthetic-workspace',role:'viewer'});});
  await expect(page.locator('.list').first()).toHaveAttribute('data-list-color','frost-blue');await expect(page.locator('.list').nth(1)).toHaveAttribute('data-list-color','frost-blue');expect(canvas).toBe('classic-flow');
});

test('Cancel, visible Close, Escape, and storage failure preserve the prior per-list setting',async({page})=>{
  await page.addInitScript(()=>{const set=Storage.prototype.setItem;Storage.prototype.setItem=function(key,value){if(key==='flowboard-list-appearances')throw new DOMException('quota','QuotaExceededError');return set.call(this,key,value);};});
  await openReady(page);await openSyntheticBoard(page);await openAppearance(page);await page.locator('[name="list-color"][value="pale-aqua"]').check();await page.getByRole('button',{name:'Cancel'}).click();await expect(page.locator('.list').first()).toHaveAttribute('data-list-color','standard');await expect(page.locator('.list').first().locator('.list-menu')).toBeFocused();
  await openAppearance(page);await page.locator('[name="list-color"][value="blush-clay"]').check();await page.locator('.dialog-close[aria-label="Close list appearance"]').click();await expect(page.locator('.list').first()).toHaveAttribute('data-list-color','standard');await expect(page.locator('.list').first().locator('.list-menu')).toBeFocused();
  await openAppearance(page);await page.locator('[name="list-color"][value="pale-aqua"]').check();await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toBeHidden();await expect(page.locator('.list').first()).toHaveAttribute('data-list-color','standard');await expect(page.locator('.list').first().locator('.list-menu')).toBeFocused();
  await openAppearance(page);await page.locator('[name="list-color"][value="blush-clay"]').check();await page.getByRole('button',{name:'Save list appearance'}).click();await expect(page.getByRole('dialog')).toBeVisible();await expect(page.getByRole('dialog').getByRole('status')).toContainText('could not be saved');await expect(page.locator('.list').first()).toHaveAttribute('data-list-color','blush-clay');expect(await page.evaluate(()=>({workspace:localStorage.getItem('flowboard-workspace'),appearance:localStorage.getItem('flowboard-appearance'),perList:localStorage.getItem('flowboard-list-appearances')}))).toEqual({workspace:'{"sentinel":"synthetic-workspace-bytes"}',appearance:'{"sentinel":"synthetic-global-appearance-bytes"}',perList:null});
});

test('per-list appearance dialog fits target desktop, tablet, and narrow viewports',async({page})=>{
  const sizes=[{width:1440,height:900},{width:960,height:720},{width:390,height:844},{width:320,height:720},{width:844,height:390}];
  await openReady(page);await openSyntheticBoard(page);
  for(const size of sizes){await page.setViewportSize(size);await openMenu(page);await page.locator('.list-menu-panel:visible').getByRole('menuitem',{name:'List appearance'}).click();const dialog=page.getByRole('dialog'),close=dialog.locator('.dialog-close');await expect(close).toBeVisible();const box=await dialog.evaluate(el=>{const r=el.getBoundingClientRect();return{left:r.left,right:r.right,width:r.width,scrollWidth:el.scrollWidth,clientWidth:el.clientWidth,screenWidth:innerWidth,screenHeight:innerHeight};});expect(box.left).toBeGreaterThanOrEqual(0);expect(box.right).toBeLessThanOrEqual(box.screenWidth+1);expect(box.scrollWidth).toBeLessThanOrEqual(box.clientWidth+1);await dialog.getByRole('button',{name:'Save list appearance'}).scrollIntoViewIfNeeded();await expect(dialog.getByRole('button',{name:'Save list appearance'})).toBeVisible();const lastPalette=dialog.locator('.appearance-palettes .appearance-option:has(input[name="list-color"][value="pale-aqua"])');await lastPalette.scrollIntoViewIfNeeded();await expect(lastPalette).toBeInViewport();await expect(dialog.getByRole('button',{name:'Save list appearance'})).toBeVisible();const header=await dialog.locator('.card-dialog-header').evaluate(el=>{const r=el.getBoundingClientRect(),d=el.closest('dialog').getBoundingClientRect(),e=el.querySelector('.eyebrow').getBoundingClientRect();return{dialogTop:d.top,headerTop:r.top,headerBottom:r.bottom,eyebrowTop:e.top,eyebrowBottom:e.bottom};});expect(header.headerTop).toBeGreaterThanOrEqual(header.dialogTop);expect(header.eyebrowTop).toBeGreaterThanOrEqual(header.dialogTop);expect(header.eyebrowBottom).toBeLessThanOrEqual(header.headerBottom);await page.screenshot({path:`artifacts/per-list-background-implementation/continued-validation/per-list-visual-final-run/${size.width}x${size.height}.png`});await page.keyboard.press('Escape');await expect(dialog).toBeHidden();}
});
