import {readFile,writeFile} from 'node:fs/promises';
import {chromium} from 'playwright';
const ids=['classic-flow','ocean-slate','lagoon','sage-studio','warm-sand','lavender-mist','dusk-plum','graphite'];
const names={'classic-flow':'Classic Flow','ocean-slate':'Ocean Slate','lagoon':'Lagoon','sage-studio':'Sage Studio','warm-sand':'Warm Sand','lavender-mist':'Lavender Mist','dusk-plum':'Dusk Plum','graphite':'Graphite'};
const images=await Promise.all(ids.map(async id=>`<figure><figcaption>${names[id]}</figcaption><img alt="${names[id]} actual Flowboard palette" src="data:image/png;base64,${(await readFile(`artifacts/aesthetic/step-04/${id}-desktop-1440x900.png`)).toString('base64')}" /></figure>`));
const html=`<!doctype html><meta charset="utf-8"><title>Flowboard palette comparison</title><style>*{box-sizing:border-box}body{margin:0;padding:20px;background:#eef2f7;color:#172b4d;font:14px system-ui}h1{margin:0 0 4px;font-size:22px}p{margin:0 0 16px;color:#526078}.grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}figure{margin:0;overflow:hidden;border:1px solid #d6dee9;border-radius:10px;background:#fff;box-shadow:0 2px 8px #091e4214}figcaption{padding:8px 10px;font-weight:750}img{display:block;width:100%;height:auto}footer{margin-top:14px;color:#526078;font-size:12px}</style><h1>Flowboard actual-app palette comparison</h1><p>Step 4 evidence. Identical synthetic 10-card fixture at 1440px. Not production data and not yet a user-selectable preference.</p><main class="grid">${images.join('')}</main><footer>Contrast, dark variants, solid finishes, and interaction states require separate qualification.</footer>`;
await writeFile('artifacts/aesthetic/step-04/palette-comparison.html',html);
const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Google/Chrome/Application/chrome.exe'});
try {const page=await browser.newPage({viewport:{width:1400,height:1800}});await page.setContent(html);await page.screenshot({path:'artifacts/aesthetic/step-04/palette-comparison.png',fullPage:true});console.log(JSON.stringify({palettes:ids.length,comparison:'artifacts/aesthetic/step-04/palette-comparison.png'}));}finally{await browser.close();}
