import {chromium} from 'playwright';
import {readFile,writeFile} from 'node:fs/promises';
import {execFileSync} from 'node:child_process';
import {PRODUCTION_SOURCE_FILES} from '../../scripts/source-budget.mjs';
const dir='artifacts/aesthetic-planning';
const palettes=JSON.parse(await readFile(`${dir}/palettes.json`,'utf8'));
let workingBytes=0,gitBytes=0,crlfPairs=0;
for(const file of PRODUCTION_SOURCE_FILES){const content=await readFile(file);workingBytes+=content.length;gitBytes+=execFileSync('git',['show',`HEAD:${file}`]).length;crlfPairs+=(content.toString().match(/\r\n/g)||[]).length;}
const budget={workingBytes,gitBytes,crlfPairs,workingHeadroom:217500-workingBytes,gitHeadroom:217500-gitBytes};
await writeFile(`${dir}/source-baseline.json`,JSON.stringify(budget,null,2));
const html=`<!doctype html><html lang="en"><meta charset="utf-8"><title>Flowboard canvas concepts</title><style>
*{box-sizing:border-box}body{margin:0;padding:32px;background:#f0f3f7;color:#172b4d;font:14px/1.45 system-ui}h1{font-size:26px;margin:0 0 4px}header p{margin:0 0 22px;color:#526078}.grid{display:grid;grid-template-columns:1fr 1fr;gap:20px}.tile{background:white;border:1px solid #d6dee9;border-radius:12px;overflow:hidden}.caption{padding:12px 16px;display:flex;justify-content:space-between;align-items:center}.caption strong{font-size:16px}.caption small{color:#526078}.scene{padding:18px;background:linear-gradient(135deg,var(--a),var(--b));color:var(--ink)}.bar{display:flex;justify-content:space-between;font-weight:650;margin-bottom:14px}.bar span{font-weight:400}.lanes{display:grid;grid-template-columns:1fr 1fr;gap:12px}.lane{background:#edf1f6;color:#172b4d;padding:10px;border:1px solid #d6dee9;border-radius:10px}.lane>b{font-size:12px}.card{padding:10px;background:#fff;margin-top:8px;border:1px solid #e0e5ed;border-radius:7px;font-size:12px}.meta{margin-top:9px;display:flex;align-items:center;justify-content:space-between;color:#526078;font-size:11px}.person{border-radius:50%;background:#dbe4f1;width:24px;height:24px;display:grid;place-items:center;font-size:9px;font-weight:650}.variants{display:flex;gap:7px;align-items:center;padding:10px 16px;font-size:11px;color:#526078}.swatch{width:42px;height:22px;border-radius:4px;border:1px solid #d6dee9}.variants code{margin-left:auto;font-size:10px}footer{margin-top:18px;color:#526078;font-size:12px}
</style><header><h1>Flowboard canvas concepts</h1><p>Proposed directions, not implemented UI. Light cards and columns on gradient canvases. Solid and dark alternatives shown as swatches.</p></header><main class="grid">${palettes.map(p=>`<section class="tile"><div class="caption"><strong>${p.name}</strong><small>${p.note}</small></div><div class="scene" style="--a:${p.light[0]};--b:${p.light[1]};--ink:${p.ink}"><div class="bar">Project workspace<span>Board actions</span></div><div class="lanes"><div class="lane"><b>To do</b><div class="card">Prepare the weekly update<div class="meta">Due tomorrow <span class="person">AL</span></div></div></div><div class="lane"><b>In progress</b><div class="card">Review the launch checklist<div class="meta">Checklist 2/4 <span class="person">SK</span></div></div></div></div></div><div class="variants"><span class="swatch" style="background:${p.solid}"></span>Solid<span class="swatch" style="background:linear-gradient(135deg,${p.dark.join(',')})"></span>Dark<code>${p.light.join(' → ')}</code></div></section>`).join('')}</main><footer>Illustrative synthetic cards and initials only. Exact contrast, full dialogs, and real avatar behavior require implementation qualification.</footer></html>`;
await writeFile(`${dir}/canvas-concepts.html`,html);
const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Google/Chrome/Application/chrome.exe'});
try {const page=await browser.newPage({viewport:{width:1200,height:1500}});await page.setContent(html);await page.screenshot({path:`${dir}/canvas-concepts.png`,fullPage:true});console.log(JSON.stringify({palettes:palettes.length,budget,preview:'canvas-concepts.png'}));}finally{await browser.close();}
