import {applyCanvasPalette, getCanvasPalette} from './canvas-palettes.js';

const DEFAULT = Object.freeze({version:1, mode:'system', canvas:'classic-flow', finish:'gradient', showPhotos:true});
const modes = new Set(['system','light','dark']), finishes = new Set(['gradient','solid']);
let q,f,c,d,r = false, rf = null;
const root = document.documentElement;
const adapter = () => globalThis.FlowboardRuntime.localAdapter;
const valid = value => value && value.version === 1 && modes.has(value.mode) && getCanvasPalette(value.canvas) && finishes.has(value.finish) && typeof value.showPhotos === 'boolean';
const normalize = value => valid(value) ? {...value} : {...DEFAULT, mode:modes.has(root.dataset.appearanceMode) ? root.dataset.appearanceMode : DEFAULT.mode};
const announce = text => { const node=document.querySelector('#announcer'); if(node) { node.textContent=''; requestAnimationFrame(() => { node.textContent=text; }); } };
const css = `.appearance-dialog{width:min(760px,calc(100vw - 32px))}.appearance-card{padding:22px}.appearance-group{margin:20px 0 0;padding:0;border:0}.appearance-group legend{margin-bottom:9px;padding:0;color:var(--ink);font-size:13px;font-weight:800}.appearance-options{display:flex;flex-wrap:wrap;gap:8px}.appearance-option{display:flex;align-items:center;gap:8px;min-height:40px;padding:8px 10px;color:var(--ink);border:1px solid var(--line);border-radius:8px;background:var(--surface);font-weight:650}.appearance-option:has(input:checked){border-color:var(--accent);background:var(--accent-soft)}.appearance-option input{width:17px;height:17px;margin:0;accent-color:var(--accent)}.appearance-palettes{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:8px}.appearance-palettes .appearance-option{min-height:62px;display:grid;grid-template-columns:17px 44px minmax(0,1fr);align-items:start;column-gap:8px}.palette-swatch{grid-column:2;grid-row:1 / span 2;flex:none;width:44px;height:32px;border:1px solid var(--line);border-radius:7px;background:linear-gradient(135deg,var(--swatch-start),var(--swatch-end))}.appearance-palettes .appearance-option>span:not(.palette-swatch){grid-column:3;min-width:0;overflow-wrap:anywhere}.appearance-palettes .appearance-option>small{grid-column:3;color:var(--muted);font-size:11px;font-weight:500;line-height:1.25;overflow-wrap:anywhere}.appearance-actions{margin-top:22px}.appearance-action-spacer{flex:1}@media(max-width:600px){.appearance-palettes{grid-template-columns:repeat(2,minmax(0,1fr))}.appearance-actions{flex-wrap:wrap}.appearance-action-spacer{display:none}.appearance-actions .button{flex:1}}`;
const markup=`<dialog id="appearance-dialog" class="dialog appearance-dialog" aria-labelledby="appearance-heading" aria-describedby="appearance-scope"><form id="appearance-form" class="appearance-card"><header class="card-dialog-header"><div><p class="eyebrow">Appearance</p><h2 id="appearance-heading">Personalize Flowboard</h2></div><button id="close-appearance-dialog" class="dialog-close" type="button" aria-label="Close appearance"><svg><use href="#icon-close"></use></svg></button></header><p id="appearance-scope" class="collaboration-notice">Appearance applies only to this browser and changes only your view. Profile photos are managed in Account.</p><fieldset class="appearance-group"><legend>Theme</legend><div class="appearance-options"><label class="appearance-option"><input type="radio" name="appearance-mode" value="system"><span>System</span></label><label class="appearance-option"><input type="radio" name="appearance-mode" value="light"><span>Light</span></label><label class="appearance-option"><input type="radio" name="appearance-mode" value="dark"><span>Dark</span></label></div></fieldset><fieldset class="appearance-group"><legend>Canvas</legend><div id="appearance-palettes" class="appearance-palettes"></div></fieldset><fieldset class="appearance-group"><legend>Finish</legend><div class="appearance-options"><label class="appearance-option"><input type="radio" name="appearance-finish" value="gradient"><span>Gradient</span></label><label class="appearance-option"><input type="radio" name="appearance-finish" value="solid"><span>Solid color</span></label></div></fieldset><fieldset class="appearance-group"><legend>Assignee images</legend><div class="appearance-options"><label class="appearance-option"><input type="radio" name="appearance-photos" value="photos"><span>Show profile photos when available</span></label><label class="appearance-option"><input type="radio" name="appearance-photos" value="initials"><span>Use initials</span></label></div></fieldset><p id="appearance-status" class="account-status" role="status" aria-live="polite"></p><div class="dialog-actions appearance-actions"><button id="reset-appearance" class="button button-quiet" type="button">Reset to defaults</button><span class="appearance-action-spacer"></span><button id="cancel-appearance" class="button button-quiet" type="button">Cancel</button><button class="button button-primary" type="submit">Save appearance</button></div></form></dialog>`;
function setupStyle() { if(document.querySelector('#appearance-style')) return; const style=document.createElement('style'); style.id='appearance-style'; style.textContent=css; document.head.append(style); }
function apply(value) { const dark=value.mode==='dark'||value.mode==='system'&&matchMedia('(prefers-color-scheme: dark)').matches; root.dataset.appearanceMode=value.mode; root.dataset.appearancePhotos=value.showPhotos?'photos':'initials'; root.dataset.theme=dark?'dark':'light'; applyCanvasPalette(value.canvas,value.finish,dark?'dark':'light'); const meta=document.querySelector('meta[name="theme-color"]'); if(meta) meta.content=dark?'#182d54':'#0f6cbd'; window.dispatchEvent(new CustomEvent('flowboard:appearance-change',{detail:{...value}})); }
function setChecked(name,value) { const input=f.querySelector(`input[name="${name}"][value="${value}"]`); if(input) input.checked=true; }
function renderPalettes() { const host=document.querySelector('#appearance-palettes'); host.replaceChildren(); globalThis.FlowboardRuntime.canvasPalettes.forEach(palette=>{ const details=getCanvasPalette(palette.id), label=document.createElement('label'), input=document.createElement('input'), swatch=document.createElement('span'), text=document.createElement('span'), note=document.createElement('small'); label.className='appearance-option'; input.type='radio'; input.name='appearance-canvas'; input.value=palette.id; swatch.className='palette-swatch'; swatch.setAttribute('aria-hidden','true'); swatch.style.setProperty('--swatch-start',details.light[0]); swatch.style.setProperty('--swatch-end',details.light[1]); text.textContent=palette.name; note.textContent=palette.note; label.append(input,swatch,text,note); host.append(label); }); }
function render() { setChecked('appearance-mode',d.mode); setChecked('appearance-canvas',d.canvas); setChecked('appearance-finish',d.finish); setChecked('appearance-photos',d.showPhotos?'photos':'initials'); }
function readDraft() { return {version:1,mode:f.querySelector('input[name="appearance-mode"]:checked')?.value||DEFAULT.mode,canvas:f.querySelector('input[name="appearance-canvas"]:checked')?.value||DEFAULT.canvas,finish:f.querySelector('input[name="appearance-finish"]:checked')?.value||DEFAULT.finish,showPhotos:f.querySelector('input[name="appearance-photos"]:checked')?.value!=='initials'}; }
function preview() { d=readDraft(); apply(d); document.querySelector('#appearance-status').textContent='Preview only. Save appearance to keep these choices in this browser.'; }
function restore() { d={...c}; render(); apply(c); }
function closeWithoutSave() { restore(); q.close(); }
function initialize() { if(r)return;r=true; setupStyle(); if(!document.querySelector('#appearance-dialog')) document.body.insertAdjacentHTML('beforeend',markup); q=document.querySelector('#appearance-dialog'); f=document.querySelector('#appearance-form'); renderPalettes(); c=normalize(adapter().loadAppearance?.()); apply(c); f.addEventListener('change',preview); f.addEventListener('submit',event=>{event.preventDefault(); const next=readDraft(), result=adapter().saveAppearance?.(next); if(!result?.ok) { document.querySelector('#appearance-status').textContent='Appearance could not be saved. Your choices are still previewed; try again or Cancel.'; return; } c=next; d={...next}; apply(c); document.querySelector('#appearance-status').textContent='Appearance saved in this browser.'; announce('Appearance saved in this browser.'); q.close(); }); document.querySelector('#close-appearance-dialog').addEventListener('click',closeWithoutSave); document.querySelector('#cancel-appearance').addEventListener('click',closeWithoutSave); document.querySelector('#reset-appearance').addEventListener('click',()=>{d={...DEFAULT};render();preview();}); q.addEventListener('cancel',event=>{event.preventDefault();closeWithoutSave();}); q.addEventListener('close',()=>{(rf?.offsetParent?rf:document.querySelector('#account-button')||document.querySelector('#theme-toggle'))?.focus();rf=null;}); }
export function openAppearance(opener = document.activeElement) { initialize(); rf=opener; d={...c}; render(); document.querySelector('#appearance-status').textContent=''; q.showModal(); f.querySelector('input:checked')?.focus(); }
