// Anonymous live visual audit. No sign-in, cloud access, or production mutation.
const fs=require('node:fs'),path=require('node:path');
const root=__dirname,tmp=path.join(root,'tmp');fs.mkdirSync(tmp,{recursive:true});
process.env.TEMP=tmp;process.env.TMP=tmp;process.env.TMPDIR=tmp;
const {chromium}=require('playwright');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Google/Chrome/Application/chrome.exe'});const results=[];const errors={console:0,page:0};
const save=async(page,name)=>{await page.screenshot({path:path.join(root,name+'.png'),fullPage:false});const metrics=await page.evaluate(()=>{const box=e=>{const r=e.getBoundingClientRect(),s=getComputedStyle(e);return {x:r.x,y:r.y,width:r.width,height:r.height,font:s.fontFamily,fontSize:s.fontSize,marginBottom:s.marginBottom};};return{viewport:{width:innerWidth,height:innerHeight},documentWidth:document.documentElement.scrollWidth,boardHeader:box(document.querySelector('.board-header')),controls:['#collaboration-summary','#board-menu','details.collaboration-notice'].map(q=>({selector:q,...box(document.querySelector(q))})),dialog:[...document.querySelectorAll('dialog[open]')].map(e=>({id:e.id,...box(e),scrollWidth:e.scrollWidth,clientWidth:e.clientWidth}))};});results.push({name,...metrics});fs.writeFileSync(path.join(root,'live-audit.json'),JSON.stringify({scope:'anonymous public UI only',errors,results},null,2));};
try{for(const [w,h]of [[1280,720],[1440,900],[1920,1080],[960,720],[390,844],[320,720]]){const context=await browser.newContext({viewport:{width:w,height:h}});const page=await context.newPage();page.on('console',m=>{if(m.type()==='error')errors.console++;});page.on('pageerror',()=>errors.page++);await page.goto('https://kcchanai.github.io/UH-Flowboard/?visual-audit='+Date.now(),{waitUntil:'networkidle'});await page.locator('.card-open').first().waitFor();await save(page,`board-${w}x${h}`);
if(w===1440){await page.locator('#view-toggle').click();await page.locator('#list-view-table').waitFor();await save(page,'list-desktop');await page.locator('#view-toggle').click();await page.locator('.card-open').first().waitFor();await page.locator('.card-open').first().click();await page.locator('#card-dialog[open]').waitFor();await save(page,'card-desktop');await page.locator('#close-card-dialog').click();await page.locator('#account-button').click();await page.locator('#account-dialog[open]').waitFor();await save(page,'account-anonymous');await page.locator('#close-account-dialog').click();await page.getByRole('button',{name:'Open appearance settings'}).click();await page.locator('#appearance-dialog[open]').waitFor();await save(page,'appearance-desktop');await page.getByRole('button',{name:'Close appearance'}).click();await page.locator('#quick-add-card').click();await page.locator('#quick-add-dialog[open]').waitFor();await save(page,'quick-add-desktop');await page.keyboard.press('Escape');await page.locator('#quick-add-dialog').waitFor({state:'hidden'});await page.locator('#theme-toggle').click();await page.locator('#appearance-dialog[open]').waitFor();await page.locator('input[name="appearance-mode"][value="dark"]').check();await page.getByRole('button',{name:'Save appearance',exact:true}).click();await page.locator('#appearance-dialog').waitFor({state:'hidden'});await page.waitForFunction(()=>document.documentElement.dataset.theme==='dark');await save(page,'dark-desktop');}
await context.close();}
console.log(JSON.stringify({captures:results.length,consoleErrors:errors.console,pageErrors:errors.page,documentOverflow:results.filter(r=>r.documentWidth>r.viewport.width).map(r=>r.name),controls:results.filter(r=>r.name==='board-1440x900').map(r=>r.controls)},null,2));}finally{await browser.close();fs.rmSync(tmp,{recursive:true,force:true});}})().catch(()=>{console.error('Anonymous visual audit failed; inspect script selectors and partial JSON.');process.exitCode=1;});
